# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def region_RPN_tokens(index, cell, data):
    offset = cell["region_RPN_tokens_offset"]
    return data[offset + index]


@trace.njit()
def region_RPN_tokens_all(cell, data):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def region_RPN_tokens_last(cell, data):
    start = cell["region_RPN_tokens_offset"]
    size = cell["region_RPN_tokens_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def region_RPN_tokens_chunk(start, length, cell, data):
    start += cell["region_RPN_tokens_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def surface_IDs(index, cell, data):
    offset = cell["surface_IDs_offset"]
    return data[offset + index]


@trace.njit()
def surface_IDs_all(cell, data):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    return data[start:end]


@trace.njit()
def surface_IDs_last(cell, data):
    start = cell["surface_IDs_offset"]
    size = cell["N_surface"]
    end = start + size
    return data[end - 1]


@trace.njit()
def surface_IDs_chunk(start, length, cell, data):
    start += cell["surface_IDs_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def tally_IDs(index, cell, data):
    offset = cell["tally_IDs_offset"]
    return data[offset + index]


@trace.njit()
def tally_IDs_all(cell, data):
    start = cell["tally_IDs_offset"]
    size = cell["N_tally"]
    end = start + size
    return data[start:end]


@trace.njit()
def tally_IDs_last(cell, data):
    start = cell["tally_IDs_offset"]
    size = cell["N_tally"]
    end = start + size
    return data[end - 1]


@trace.njit()
def tally_IDs_chunk(start, length, cell, data):
    start += cell["tally_IDs_offset"]
    end = start + length
    return data[start:end]
