# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def xs(index, electron_reaction, data):
    offset = electron_reaction["xs_offset"]
    return data[offset + index]


@trace.njit()
def xs_all(electron_reaction, data):
    start = electron_reaction["xs_offset"]
    size = electron_reaction["xs_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def xs_last(electron_reaction, data):
    start = electron_reaction["xs_offset"]
    size = electron_reaction["xs_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def xs_chunk(start, length, electron_reaction, data):
    start += electron_reaction["xs_offset"]
    end = start + length
    return data[start:end]
