# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def subshell_x_IDs(index, electron_ionization_reaction, data):
    offset = electron_ionization_reaction["subshell_x_IDs_offset"]
    return data[offset + index]


@trace.njit()
def subshell_x_IDs_all(electron_ionization_reaction, data):
    start = electron_ionization_reaction["subshell_x_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_x"]
    end = start + size
    return data[start:end]


@trace.njit()
def subshell_x_IDs_last(electron_ionization_reaction, data):
    start = electron_ionization_reaction["subshell_x_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_x"]
    end = start + size
    return data[end - 1]


@trace.njit()
def subshell_x_IDs_chunk(start, length, electron_ionization_reaction, data):
    start += electron_ionization_reaction["subshell_x_IDs_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def subshell_product_IDs(index, electron_ionization_reaction, data):
    offset = electron_ionization_reaction["subshell_product_IDs_offset"]
    return data[offset + index]


@trace.njit()
def subshell_product_IDs_all(electron_ionization_reaction, data):
    start = electron_ionization_reaction["subshell_product_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_product"]
    end = start + size
    return data[start:end]


@trace.njit()
def subshell_product_IDs_last(electron_ionization_reaction, data):
    start = electron_ionization_reaction["subshell_product_IDs_offset"]
    size = electron_ionization_reaction["N_subshell_product"]
    end = start + size
    return data[end - 1]


@trace.njit()
def subshell_product_IDs_chunk(start, length, electron_ionization_reaction, data):
    start += electron_ionization_reaction["subshell_product_IDs_offset"]
    end = start + length
    return data[start:end]
