# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def value(index, nbody_distribution, data):
    offset = nbody_distribution["value_offset"]
    return data[offset + index]


@trace.njit()
def value_all(nbody_distribution, data):
    start = nbody_distribution["value_offset"]
    size = nbody_distribution["value_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def value_last(nbody_distribution, data):
    start = nbody_distribution["value_offset"]
    size = nbody_distribution["value_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def value_chunk(start, length, nbody_distribution, data):
    start += nbody_distribution["value_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def pdf(index, nbody_distribution, data):
    offset = nbody_distribution["pdf_offset"]
    return data[offset + index]


@trace.njit()
def pdf_all(nbody_distribution, data):
    start = nbody_distribution["pdf_offset"]
    size = nbody_distribution["pdf_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def pdf_last(nbody_distribution, data):
    start = nbody_distribution["pdf_offset"]
    size = nbody_distribution["pdf_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def pdf_chunk(start, length, nbody_distribution, data):
    start += nbody_distribution["pdf_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def cdf(index, nbody_distribution, data):
    offset = nbody_distribution["cdf_offset"]
    return data[offset + index]


@trace.njit()
def cdf_all(nbody_distribution, data):
    start = nbody_distribution["cdf_offset"]
    size = nbody_distribution["cdf_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def cdf_last(nbody_distribution, data):
    start = nbody_distribution["cdf_offset"]
    size = nbody_distribution["cdf_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def cdf_chunk(start, length, nbody_distribution, data):
    start += nbody_distribution["cdf_offset"]
    end = start + length
    return data[start:end]
