# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def value(index, pmf_distribution, data):
    offset = pmf_distribution["value_offset"]
    return data[offset + index]


@trace.njit()
def value_all(pmf_distribution, data):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def value_last(pmf_distribution, data):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def value_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["value_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def pmf(index, pmf_distribution, data):
    offset = pmf_distribution["pmf_offset"]
    return data[offset + index]


@trace.njit()
def pmf_all(pmf_distribution, data):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def pmf_last(pmf_distribution, data):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def pmf_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["pmf_offset"]
    end = start + length
    return data[start:end]


@trace.njit()
def cmf(index, pmf_distribution, data):
    offset = pmf_distribution["cmf_offset"]
    return data[offset + index]


@trace.njit()
def cmf_all(pmf_distribution, data):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    return data[start:end]


@trace.njit()
def cmf_last(pmf_distribution, data):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    return data[end - 1]


@trace.njit()
def cmf_chunk(start, length, pmf_distribution, data):
    start += pmf_distribution["cmf_offset"]
    end = start + length
    return data[start:end]
