# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def xs(index, electron_reaction, data, value):
    offset = electron_reaction["xs_offset"]
    data[offset + index] = value


@trace.njit()
def xs_all(electron_reaction, data, value):
    start = electron_reaction["xs_offset"]
    size = electron_reaction["xs_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def xs_last(electron_reaction, data, value):
    start = electron_reaction["xs_offset"]
    size = electron_reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def xs_chunk(start, length, electron_reaction, data, value):
    start += electron_reaction["xs_offset"]
    end = start + length
    data[start:end] = value
