# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def grid(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["grid_offset"]
    data[offset + index] = value


@trace.njit()
def grid_all(multi_table_distribution, data, value):
    start = multi_table_distribution["grid_offset"]
    size = multi_table_distribution["grid_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def grid_last(multi_table_distribution, data, value):
    start = multi_table_distribution["grid_offset"]
    size = multi_table_distribution["grid_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def grid_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["grid_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def offset(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["offset_offset"]
    data[offset + index] = value


@trace.njit()
def offset_all(multi_table_distribution, data, value):
    start = multi_table_distribution["offset_offset"]
    size = multi_table_distribution["offset_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def offset_last(multi_table_distribution, data, value):
    start = multi_table_distribution["offset_offset"]
    size = multi_table_distribution["offset_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def offset_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["offset_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def value(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["value_offset"]
    data[offset + index] = value


@trace.njit()
def value_all(multi_table_distribution, data, value):
    start = multi_table_distribution["value_offset"]
    size = multi_table_distribution["value_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def value_last(multi_table_distribution, data, value):
    start = multi_table_distribution["value_offset"]
    size = multi_table_distribution["value_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def value_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["value_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def pdf(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["pdf_offset"]
    data[offset + index] = value


@trace.njit()
def pdf_all(multi_table_distribution, data, value):
    start = multi_table_distribution["pdf_offset"]
    size = multi_table_distribution["pdf_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def pdf_last(multi_table_distribution, data, value):
    start = multi_table_distribution["pdf_offset"]
    size = multi_table_distribution["pdf_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def pdf_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["pdf_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def cdf(index, multi_table_distribution, data, value):
    offset = multi_table_distribution["cdf_offset"]
    data[offset + index] = value


@trace.njit()
def cdf_all(multi_table_distribution, data, value):
    start = multi_table_distribution["cdf_offset"]
    size = multi_table_distribution["cdf_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def cdf_last(multi_table_distribution, data, value):
    start = multi_table_distribution["cdf_offset"]
    size = multi_table_distribution["cdf_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def cdf_chunk(start, length, multi_table_distribution, data, value):
    start += multi_table_distribution["cdf_offset"]
    end = start + length
    data[start:end] = value
