# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def xs(index, neutron_reaction, data, value):
    offset = neutron_reaction["xs_offset"]
    data[offset + index] = value


@trace.njit()
def xs_all(neutron_reaction, data, value):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def xs_last(neutron_reaction, data, value):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def xs_chunk(start, length, neutron_reaction, data, value):
    start += neutron_reaction["xs_offset"]
    end = start + length
    data[start:end] = value
