# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def coefficients(index, polynomial_data, data, value):
    offset = polynomial_data["coefficients_offset"]
    data[offset + index] = value


@trace.njit()
def coefficients_all(polynomial_data, data, value):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def coefficients_last(polynomial_data, data, value):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def coefficients_chunk(start, length, polynomial_data, data, value):
    start += polynomial_data["coefficients_offset"]
    end = start + length
    data[start:end] = value
