# The following is automatically generated by code_factory.py

import mcdc.trace as trace


@trace.njit()
def x(index, table_data, data, value):
    offset = table_data["x_offset"]
    data[offset + index] = value


@trace.njit()
def x_all(table_data, data, value):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def x_last(table_data, data, value):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def x_chunk(start, length, table_data, data, value):
    start += table_data["x_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def y(index, table_data, data, value):
    offset = table_data["y_offset"]
    data[offset + index] = value


@trace.njit()
def y_all(table_data, data, value):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def y_last(table_data, data, value):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def y_chunk(start, length, table_data, data, value):
    start += table_data["y_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def interpolations(index, table_data, data, value):
    offset = table_data["interpolations_offset"]
    data[offset + index] = value


@trace.njit()
def interpolations_all(table_data, data, value):
    start = table_data["interpolations_offset"]
    size = table_data["interpolations_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def interpolations_last(table_data, data, value):
    start = table_data["interpolations_offset"]
    size = table_data["interpolations_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def interpolations_chunk(start, length, table_data, data, value):
    start += table_data["interpolations_offset"]
    end = start + length
    data[start:end] = value


@trace.njit()
def interpolation_boundaries(index, table_data, data, value):
    offset = table_data["interpolation_boundaries_offset"]
    data[offset + index] = value


@trace.njit()
def interpolation_boundaries_all(table_data, data, value):
    start = table_data["interpolation_boundaries_offset"]
    size = table_data["interpolation_boundaries_length"]
    end = start + size
    data[start:end] = value


@trace.njit()
def interpolation_boundaries_last(table_data, data, value):
    start = table_data["interpolation_boundaries_offset"]
    size = table_data["interpolation_boundaries_length"]
    end = start + size
    data[end - 1] = value


@trace.njit()
def interpolation_boundaries_chunk(start, length, table_data, data, value):
    start += table_data["interpolation_boundaries_offset"]
    end = start + length
    data[start:end] = value
